### ISSUE TITLE
Can I get the un-merged reads from merged data?

### ISSUE THREAD

**Issue by YiweiNiu** [grenaud/leeHom#10]
Hi,

I am thinking if we can get the un-merged reads from the data merged by leeHom, since in some cases paired-end reads are needed.

Best,
Yiwei

**Comment by grenaud** [comment]
Hi Yiwei,
Thank you for your message! I'll try to answer your question in two ways. 

1) if you have the raw reads, you can carry over the raw paired reads for the merged sequences using the "--keepOrig" flag if you have bam input as you flag those as being QC failed. You can recover them in the output bam. If you have raw reads fastq, you can easily convert them to bam. The output bam can be converted to fastq.
2) if someone gives you a file that has been processed by leeHom and asks you to recover the original raw reads based on that file alone, this is impossible. There is a high number of raw reads that can give you the same output DNA sequence.

I hope I've answered your question :-) Let me know otherwise.

**Comment by YiweiNiu** [comment]
Thank you for your promote reply! Now I know what to do. Thank you!
